-- Insert 8 mock editorial blog posts corresponding to your new minimalist aesthetic

INSERT INTO public.posts (title, slug, excerpt, content, published) VALUES
('The Brutalist Approach to Component Design', 'brutalist-component-design', 'Stripping away the unnecessary to reveal the raw functional beauty of React components.', '<p>When we design components, we often layer them with gradients, shadows, and unnecessary spacing. What if we stripped all of that away?</p><p>Brutalist design in UI architecture focuses on the raw materials of the web: borders, stark contrast, and readable typography.</p>', true),
('Typography as the Ultimate UI Framework', 'typography-ultimate-ui', 'Why fonts like Space Grotesk and Inter are all you need to build a compelling interface.', '<p>Before you reach for complex CSS frameworks, simply look at your typography. The right font scale and pairing can do 90% of the heavy lifting for your interface.</p>', true),
('Embracing Whitespace in Modern Engineering', 'embracing-whitespace', 'Whitespace isn''t just empty space; it''s the structural foundation of your layout.', '<p>The most common mistake junior developers make is trying to fill every pixel of the screen. True editorial design breathes through its whitespace.</p>', true),
('Next.js App Router: The Editorial Paradigm', 'nextjs-app-router-editorial', 'How Server Components perfectly align with static editorial content.', '<p>Server Components allow us to query our database directly without shipping massive JavaScript bundles to the client. This is a game changer for content-heavy sites.</p>', true),
('The Fall of Glassmorphism', 'fall-of-glassmorphism', 'Why blurry backgrounds are giving way to stark, high-contrast borders.', '<p>Glassmorphism was everywhere. But user interfaces are returning to their roots: high readability, fast performance, and strong structural lines.</p>', true),
('Supabase as a Headless CMS', 'supabase-headless-cms', 'Using PostgreSQL and Row Level Security to securely manage editorial content.', '<p>You do not need a dedicated CMS if you know how to architect a good PostgreSQL schema. Supabase brings this power to frontend developers automatically.</p>', true),
('The Power of JSON-LD for Technical Blogs', 'power-of-json-ld', 'Ensuring your Next.js blog ranks perfectly on Google with precise structured data.', '<p>Search engines love structure. JSON-LD allows you to explicitly tell Google exactly what your content is, who wrote it, and when it was published.</p>', true),
('Curating the Ultimate Developer Reading List', 'ultimate-developer-reading-list', 'Eight foundational articles every modern frontend engineer needs to read.', '<p>From React design patterns to CSS grid architectures, these are the resources that shape the modern web.</p>', true);
